- name: Add database to database server
  hosts: localhost
  vars:
    main_db: <>
    postgres_auth: &postgres_auth
      login_host: <>
      login_user: <>
      login_password: <>
  tasks:
    - name: Ping PostgreSQL
      community.postgresql.postgresql_ping:
        <<: *postgres_auth
        db: "{{ main_db }}"
      register: result

    - name: Create edit user
      community.postgresql.postgresql_user:
        <<: *postgres_auth
        db: "{{ main_db }}"
        name: "edit_user"
        password: "{{ lookup('ansible.builtin.password', 'edit_user_password chars=ascii_letters') }}"
        comment: This user can edit but not change the schema

    - name: Grant usage on schema
      community.postgresql.postgresql_privs:
        <<: *postgres_auth
        db: "{{ main_db }}"
        privs: USAGE
        objs: public
        type: schema
        roles: "edit_user"

    - name: Revoke create on schema
      community.postgresql.postgresql_privs:
        <<: *postgres_auth
        db: "{{ main_db }}"
        privs: CREATE
        objs: public
        type: schema
        state: absent
        roles: "public"

    - name: Grant editing privs on existing tables
      community.postgresql.postgresql_privs:
        <<: *postgres_auth
        db: "{{ main_db }}"
        objs: ALL_IN_SCHEMA
        privs: SELECT,INSERT,UPDATE,DELETE
        type: table
        role: "edit_user"
        schema: public

    - name: Alter default privs to allow edit on db
      community.postgresql.postgresql_privs:
        <<: *postgres_auth
        db: "{{ main_db }}"
        objs: TABLES
        privs: SELECT,INSERT,UPDATE,DELETE
        type: default_privs
        role: "edit_user"
        schema: public