- name: Add database to database server
  hosts: localhost

  vars_prompt:
    - name: list_of_databases
      prompt: list_of_databases?
      private: false
    - name: login_host_prompt
      prompt: login_host?
      private: false
    - name: login_user_prompt
      prompt: login_user?
      private: false
    - name: login_password_prompt
      prompt: login_password?
    - name: read_user_password
      prompt: read_user_password?

  vars:
    postgres_auth: &postgres_auth
      login_host: "{{ login_host_prompt }}"
      login_user: "{{ login_user_prompt }}"
      login_password: "{{ login_password_prompt }}"

  tasks:
    - set_fact:
        database_list: "{{ list_of_databases.split(',') }}"

    - name: Ping PostgreSQL
      community.postgresql.postgresql_ping:
        <<: *postgres_auth
        db: "postgres"
      register: result

    - name: Create read user
      community.postgresql.postgresql_user:
        <<: *postgres_auth
        db: "postgres"
        name: "read_user"
        password: "{{ read_user_password }}"
        comment: This user can read but not change the schema

    - name: Grant usage on schema
      community.postgresql.postgresql_privs:
        <<: *postgres_auth
        db: "{{ item }}"
        privs: USAGE
        objs: public
        type: schema
        roles: "read_user"
      loop: "{{ database_list }}"

    - name: Revoke create on schema
      community.postgresql.postgresql_privs:
        <<: *postgres_auth
        db: "{{ item }}"
        privs: CREATE
        objs: public
        type: schema
        state: absent
        roles: "public"
      loop: "{{ database_list }}"

    - name: Grant reading privs on existing tables
      community.postgresql.postgresql_privs:
        <<: *postgres_auth
        db: "{{ item }}"
        objs: ALL_IN_SCHEMA
        privs: SELECT
        type: table
        role: "read_user"
        schema: public
      loop: "{{ database_list }}"

    - name: Alter default privs to allow read on db
      community.postgresql.postgresql_privs:
        <<: *postgres_auth
        db: "{{ item }}"
        objs: TABLES
        privs: SELECT
        type: default_privs
        role: "read_user"
        schema: public
      loop: "{{ database_list }}"

