- name: Add database to database server
  hosts: localhost

  vars:
    main_db: <>
    postgres_auth: &postgres_auth
      login_host: <>
      login_user: <>
      login_password: <>

  tasks:
    - name: Ping PostgreSQL
      community.postgresql.postgresql_ping:
        <<: *postgres_auth
        db: "{{ main_db }}"
      register: result
    - name: Create read user
      community.postgresql.postgresql_user:
        <<: *postgres_auth
        db: "{{ main_db }}"
        name: "read_user"
        password: "{{ lookup('ansible.builtin.password', 'read_user_password chars=ascii_letters') }}"
        comment: This user can read but not change the schema

    - name: Grant usage on schema
      community.postgresql.postgresql_privs:
        <<: *postgres_auth
        db: "{{ main_db }}"
        privs: USAGE
        objs: public
        type: schema
        roles: "read_user"

    - name: Revoke create on schema
      community.postgresql.postgresql_privs:
        <<: *postgres_auth
        db: "{{ main_db }}"
        privs: CREATE
        objs: public
        type: schema
        state: absent
        roles: "public"

    - name: Grant reading privs on existing tables
      community.postgresql.postgresql_privs:
        <<: *postgres_auth
        db: "{{ main_db }}"
        objs: ALL_IN_SCHEMA
        privs: SELECT
        type: table
        role: "read_user"
        schema: public

    - name: Alter default privs to allow read on db
      community.postgresql.postgresql_privs:
        <<: *postgres_auth
        db: "{{ main_db }}"
        objs: TABLES
        privs: SELECT
        type: default_privs
        role: "read_user"
        schema: public

